apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    # Usamos el nombre del servicio de Docker Compose como hostname interno
    url: http://prometheus:9090 
    isDefault: true
    editable: false # Evita que se modifique por error desde la UI
